version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: jctop
      POSTGRES_USER: jctop
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jctop"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - ./apps/server/.env.local
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "cd /app/apps/server && node dist/main"

volumes:
  postgres_data: