apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: JCTOP-Full-Stack
spec:
  description: JCTOP Event Management System - Full Stack Monorepo Deployment
  icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/nestjs.svg
  tags:
    - NestJS
    - Expo
    - PostgreSQL
    - Monorepo
  services:
    # PostgreSQL Database
    - name: postgres-db
      template: PREBUILT
      spec:
        source:
          image: postgres:16-alpine
        ports:
          - id: database
            port: 5432
            type: TCP
        volumes:
          - id: data
            dir: /var/lib/postgresql/data
        env:
          POSTGRES_USER:
            default: jctop
            expose: true
          POSTGRES_PASSWORD:
            generate: PASSWORD
            expose: true
          POSTGRES_DB:
            default: jctop
            expose: true

    # Backend API Service
    - name: backend-api
      template: GIT
      spec:
        source:
          type: GITHUB
          repoID: golfamigo/JCTOPV2
        build:
          dockerfile: Dockerfile.backend
        env:
          DATABASE_URL:
            default: postgresql://${postgres-db.POSTGRES_USER}:${postgres-db.POSTGRES_PASSWORD}@postgres-db:5432/${postgres-db.POSTGRES_DB}
          JWT_SECRET:
            generate: PASSWORD
          ENCRYPTION_SECRET_KEY:
            default: abcdefghijklmnopqrstuvwxyz123456
          NODE_ENV:
            default: production
        ports:
          - id: web
            port: 3000
            type: HTTP

    # Frontend Web Service
    - name: frontend-web
      template: GIT
      spec:
        source:
          type: GITHUB
          repoID: golfamigo/JCTOPV2
        build:
          dockerfile: Dockerfile.frontend
        env:
          EXPO_PUBLIC_API_URL:
            default: https://${backend-api.ZEABUR_WEB_URL}/api/v1
          NODE_ENV:
            default: production
        ports:
          - id: web
            port: 80
            type: HTTP