# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
    name: JCTOP
spec:
    description: JCTOP Event Management System
    icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/nestjs.svg
    tags:
        - NestJS
        - Expo
        - PostgreSQL
    services:
        - name: postgres
          template: POSTGRESQL
          
        - name: backend
          template: GIT
          spec:
            source:
                target: server.Dockerfile
            env:
                DATABASE_URL:
                    default: ${postgres.POSTGRES_CONNECTION_STRING}
                JWT_SECRET:
                    generate: PASSWORD
                ENCRYPTION_SECRET_KEY:
                    generate: PASSWORD
                NODE_ENV:
                    default: production
                    
        - name: frontend
          template: GIT
          spec:
            source:
                target: client.Dockerfile
            env:
                EXPO_PUBLIC_API_URL:
                    default: https://${backend.ZEABUR_WEB_URL}/api/v1