# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
    name: JCTOP Event System
spec:
    description: Event management system with NestJS backend and Expo web frontend
    icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/nestjs.svg
    coverImage: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/nestjs.svg
    variables:
        - key: PUBLIC_DOMAIN
          type: DOMAIN
          name: Frontend Domain
          description: Domain for your JCTOP frontend application
        - key: API_DOMAIN
          type: DOMAIN
          name: API Domain  
          description: Domain for your JCTOP backend API
    tags:
        - NestJS
        - React
        - PostgreSQL
        - Tool
    readme: |-
        # JCTOP Event Management System
        
        A complete event management platform with modern architecture.
        
        ## Features
        - Event creation and management
        - Ticket sales and registration
        - QR code check-in system
        - Real-time analytics dashboard
        - Multi-language support
        
        ## Services
        This template deploys:
        - PostgreSQL Database
        - NestJS Backend API  
        - Expo/React Native Web Frontend
        
        ## Post-Deployment
        After deployment, your services will be automatically configured.
        The frontend will connect to the backend API automatically.
    services:
        - name: postgresql
          icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/postgresql.svg
          template: PREBUILT
          spec:
            source:
                image: postgres:16-alpine
            ports:
                - id: database
                  port: 5432
                  type: TCP
            volumes:
                - id: data
                  dir: /var/lib/postgresql/data
            env:
                POSTGRES_DB:
                    default: jctop
                POSTGRES_USER:
                    default: jctop
                POSTGRES_PASSWORD:
                    generate: PASSWORD
                    expose: true
                POSTGRES_HOST:
                    default: ${CONTAINER_HOSTNAME}
                    expose: true
                POSTGRES_PORT:
                    default: ${DATABASE_PORT}
                    expose: true
            healthCheck:
                type: TCP
                port: database
                    
        - name: backend
          icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/nestjs.svg
          dependencies:
            - postgresql
          template: GIT
          spec:
            source:
                target: /
            build:
                dockerfile: server.Dockerfile
            ports:
                - id: web
                  port: 3000
                  type: HTTP
            env:
                NODE_ENV:
                    default: production
                DATABASE_URL:
                    default: postgresql://${postgresql.POSTGRES_USER}:${postgresql.POSTGRES_PASSWORD}@${postgresql.POSTGRES_HOST}:${postgresql.POSTGRES_PORT}/${postgresql.POSTGRES_DB}
                JWT_SECRET:
                    generate: PASSWORD
                ENCRYPTION_SECRET_KEY:
                    default: abcdefghijklmnopqrstuvwxyz123456
                CORS_ORIGIN:
                    default: https://${ZEABUR_WEB_DOMAIN}
                    expose: true
                BACKEND_URL:
                    default: https://${ZEABUR_WEB_URL}
                    expose: true
                GOOGLE_CLIENT_ID:
                    default: ""
                GOOGLE_CLIENT_SECRET:
                    default: ""
            healthCheck:
                type: HTTP
                port: web
                http:
                    path: /api/v1/health
          domainKey: API_DOMAIN
                    
        - name: frontend
          icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/react.svg
          dependencies:
            - backend
          template: GIT
          spec:
            source:
                target: /
            build:
                dockerfile: client.Dockerfile
            ports:
                - id: web
                  port: 80
                  type: HTTP
            env:
                EXPO_PUBLIC_API_URL:
                    default: ${backend.BACKEND_URL}/api/v1
            healthCheck:
                type: HTTP
                port: web
                http:
                    path: /
          domainKey: PUBLIC_DOMAIN
localization:
    zh-TW:
        description: 採用 NestJS 後端和 Expo 網頁前端的活動管理系統
        variables:
            - key: PUBLIC_DOMAIN
              name: 前端網域
              description: 您的 JCTOP 前端應用程式網域
            - key: API_DOMAIN
              name: API 網域  
              description: 您的 JCTOP 後端 API 網域
        readme: |-
            # JCTOP 活動管理系統
            
            採用現代架構的完整活動管理平台。
            
            ## 功能特色
            - 活動建立與管理
            - 票券銷售與報名
            - QR Code 簽到系統
            - 即時分析儀表板
            - 多語言支援
            
            ## 服務
            此模板部署：
            - PostgreSQL 資料庫
            - NestJS 後端 API  
            - Expo/React Native 網頁前端
            
            ## 部署後設定
            部署後，您的服務將自動配置並連接。
            前端將自動連接到後端 API。