apiVersion: zeabur.com/v1
kind: Template
metadata:
    name: JCTOP Event System
spec:
    description: Event management system with database, backend and frontend
    icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/nestjs.svg
    tags:
        - NestJS
        - PostgreSQL
        - React
    services:
        - name: postgres
          template: PREBUILT
          spec:
            source:
                image: postgres:16
            ports:
                - id: database
                  port: 5432
                  type: TCP
            env:
                POSTGRES_DB:
                    default: jctop
                POSTGRES_USER:
                    default: jctop
                POSTGRES_PASSWORD:
                    generate: PASSWORD
                    
        - name: backend
          template: PREBUILT
          spec:
            source:
                image: node:18-alpine
            ports:
                - id: web
                  port: 3000
                  type: HTTP
            env:
                DATABASE_URL:
                    default: postgresql://${postgres.POSTGRES_USER}:${postgres.POSTGRES_PASSWORD}@${postgres.CONTAINER_HOSTNAME}:5432/${postgres.POSTGRES_DB}
                    
        - name: frontend  
          template: PREBUILT
          spec:
            source:
                image: nginx:alpine
            ports:
                - id: web
                  port: 80
                  type: HTTP
            env:
                API_URL:
                    default: https://${backend.ZEABUR_WEB_URL}/api/v1