apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: JCTOP-Full-Stack
spec:
  description: JCTOP Event Management System - Full Stack Monorepo Deployment
  icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/nestjs.svg
  tags:
    - NestJS
    - Expo
    - PostgreSQL
    - Monorepo
  services:
    # PostgreSQL Database
    - name: postgres
      template: PREBUILT
      spec:
        source:
          image: postgres:17
        ports:
          - id: database
            port: 5432
            type: TCP
        volumes:
          - id: data
            dir: /var/lib/postgresql/data
        env:
          POSTGRES_DATABASE:
            default: zeabur
          POSTGRES_PASSWORD:
            generate: PASSWORD
          POSTGRES_USER:
            default: root

    # Backend API Service
    - name: backend-api
      template: GIT
      spec:
        source:
          git:
            type: GITHUB
            repoID: golfamigo/JCTOPV2
        ports:
          - id: web
            port: 3000
            type: HTTP
        env:
          DATABASE_URL:
            default: postgresql://${postgres.POSTGRES_USER}:${postgres.POSTGRES_PASSWORD}@postgres:5432/${postgres.POSTGRES_DATABASE}
          JWT_SECRET:
            default: 1322fa7e9a2c139f54b2ef1f72c310e4
          ENCRYPTION_SECRET_KEY:
            default: 55f57ce844a791941af169291907e043
          NODE_ENV:
            default: production

    # Frontend Web Service
    - name: frontend-web
      template: GIT
      spec:
        source:
          git:
            type: GITHUB
            repoID: golfamigo/JCTOPV2
        ports:
          - id: web
            port: 80
            type: HTTP
        env:
          EXPO_PUBLIC_API_URL:
            default: https://${backend-api.ZEABUR_URL}/api/v1
          NODE_ENV:
            default: production