# Zeabur Template YAML for JCTOP Event Management System
# This file defines the complete infrastructure for the application
# including frontend, backend, and database services

services:
  # PostgreSQL Database Service
  database:
    name: database
    image: zeabur/postgresql:16-alpine
    env:
      POSTGRES_DB: jctop
      POSTGRES_USER: jctop
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      
  # Backend API Service (NestJS)
  server:
    name: server
    source:
      type: github
    env:
      NODE_ENV: production
      # Database connection - automatically injected from database service
      DATABASE_URL: ${database.POSTGRES_CONNECTION_STRING}
      # Security keys
      JWT_SECRET: "1322fa7e9a2c139f54b2ef1f72c310e4"
      ENCRYPTION_SECRET_KEY: "55f57ce844a791941af169291907e043"
      # CORS configuration - reference client service URL
      CORS_ORIGIN: https://${client.ZEABUR_WEB_DOMAIN}
      # Google OAuth configuration (optional)
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: https://${self.ZEABUR_WEB_DOMAIN}/api/v1/auth/google/callback
    
  # Frontend Web Service (Expo/React Native Web)
  client:
    name: client
    source:
      type: github
    env:
      # API endpoint - reference server service URL
      EXPO_PUBLIC_API_URL: https://${server.ZEABUR_WEB_DOMAIN}/api/v1